import { contextBridge, ipcRenderer } from 'electron'
import { IPC } from '../shared/ipc'
import type { AgentEvent, ParrotOptimizeEvent, CrazyParrotApi } from '../shared/types'

const api:CrazyParrotApi={
  app:{version:()=>ipcRenderer.invoke(IPC.APP_VERSION),openPath:path=>ipcRenderer.invoke(IPC.OPEN_PATH,path),preferences:()=>ipcRenderer.invoke(IPC.APP_PREFERENCES),savePreferences:input=>ipcRenderer.invoke(IPC.APP_PREFERENCES_SAVE,input),taskPolicy:()=>ipcRenderer.invoke(IPC.APP_TASK_POLICY),saveTaskPolicy:input=>ipcRenderer.invoke(IPC.APP_TASK_POLICY_SAVE,input),historyPolicy:()=>ipcRenderer.invoke(IPC.APP_HISTORY_POLICY),saveHistoryPolicy:input=>ipcRenderer.invoke(IPC.APP_HISTORY_POLICY_SAVE,input),cleanupHistory:()=>ipcRenderer.invoke(IPC.APP_HISTORY_CLEANUP),exportDiagnostics:()=>ipcRenderer.invoke(IPC.APP_DIAGNOSTICS_EXPORT),checkForUpdates:()=>ipcRenderer.invoke(IPC.APP_UPDATE_CHECK),openReleasePage:()=>ipcRenderer.invoke(IPC.APP_RELEASE_OPEN)},
  appearance:{get:()=>ipcRenderer.invoke(IPC.APPEARANCE_GET),save:input=>ipcRenderer.invoke(IPC.APPEARANCE_SAVE,input),chooseBackground:()=>ipcRenderer.invoke(IPC.APPEARANCE_CHOOSE_BACKGROUND)},
  projects:{list:()=>ipcRenderer.invoke(IPC.PROJECT_LIST),listArchived:()=>ipcRenderer.invoke(IPC.PROJECT_LIST_ARCHIVED),chooseDirectory:mode=>ipcRenderer.invoke(IPC.PROJECT_CHOOSE,mode),add:path=>ipcRenderer.invoke(IPC.PROJECT_ADD,path),get:id=>ipcRenderer.invoke(IPC.PROJECT_GET,id),archive:id=>ipcRenderer.invoke(IPC.PROJECT_ARCHIVE,id),restore:id=>ipcRenderer.invoke(IPC.PROJECT_RESTORE,id),remove:id=>ipcRenderer.invoke(IPC.PROJECT_REMOVE,id),files:(id,path,refresh)=>ipcRenderer.invoke(IPC.PROJECT_FILES,id,path,refresh),readFile:(id,path)=>ipcRenderer.invoke(IPC.PROJECT_READ_FILE,id,path)},
  parrot:{status:id=>ipcRenderer.invoke(IPC.PARROT_STATUS,id),generate:input=>ipcRenderer.invoke(IPC.PARROT_GENERATE,input),save:(id,readme,agents)=>ipcRenderer.invoke(IPC.PARROT_SAVE,id,readme,agents),approve:id=>ipcRenderer.invoke(IPC.PARROT_APPROVE,id),validate:(readme,agents)=>ipcRenderer.invoke(IPC.PARROT_VALIDATE,readme,agents),aiOptimize:input=>ipcRenderer.invoke(IPC.PARROT_AI_OPTIMIZE,input),onParrotOptimize(listener){const wrapped=(_e:Electron.IpcRendererEvent,event:ParrotOptimizeEvent)=>listener(event);ipcRenderer.on(IPC.PARROT_AI_OPTIMIZE_EVENT,wrapped);return()=>ipcRenderer.removeListener(IPC.PARROT_AI_OPTIMIZE_EVENT,wrapped)},compliance:(projectId,paths)=>ipcRenderer.invoke(IPC.PARROT_COMPLIANCE,projectId,paths),audit:(readme,agents)=>ipcRenderer.invoke(IPC.PARROT_AUDIT,readme,agents)},
  providers:{list:()=>ipcRenderer.invoke(IPC.PROVIDER_LIST),save:input=>ipcRenderer.invoke(IPC.PROVIDER_SAVE,input),remove:id=>ipcRenderer.invoke(IPC.PROVIDER_REMOVE,id),test:input=>ipcRenderer.invoke(IPC.PROVIDER_TEST,input),models:input=>ipcRenderer.invoke(IPC.PROVIDER_MODELS,input)},
  tasks:{list:id=>ipcRenderer.invoke(IPC.TASK_LIST,id),events:id=>ipcRenderer.invoke(IPC.TASK_EVENTS,id),create:(projectId,prompt,providerId,mode,parentTaskId)=>ipcRenderer.invoke(IPC.TASK_CREATE,projectId,prompt,providerId,mode,parentTaskId),reorder:(projectId,taskIds)=>ipcRenderer.invoke(IPC.TASK_REORDER,projectId,taskIds),compact:id=>ipcRenderer.invoke(IPC.TASK_COMPACT,id),approve:id=>ipcRenderer.invoke(IPC.TASK_APPROVE,id),resume:id=>ipcRenderer.invoke(IPC.TASK_RESUME,id),cancel:id=>ipcRenderer.invoke(IPC.TASK_CANCEL,id),revert:id=>ipcRenderer.invoke(IPC.TASK_REVERT,id)},
  receipts:{list:projectId=>ipcRenderer.invoke(IPC.RECEIPT_LIST,projectId),get:taskId=>ipcRenderer.invoke(IPC.RECEIPT_GET,taskId),drift:taskId=>ipcRenderer.invoke(IPC.RECEIPT_DRIFT,taskId),export:(taskId,format)=>ipcRenderer.invoke(IPC.RECEIPT_EXPORT,taskId,format)},
  snapshots:{list:projectId=>ipcRenderer.invoke(IPC.SNAPSHOT_LIST,projectId),remove:id=>ipcRenderer.invoke(IPC.SNAPSHOT_REMOVE,id),policy:()=>ipcRenderer.invoke(IPC.SNAPSHOT_POLICY),savePolicy:policy=>ipcRenderer.invoke(IPC.SNAPSHOT_POLICY_SAVE,policy),storage:()=>ipcRenderer.invoke(IPC.SNAPSHOT_STORAGE),diffContent:(taskId,path)=>ipcRenderer.invoke(IPC.SNAPSHOT_DIFF_CONTENT,taskId,path)},
  decisions:{list:projectId=>ipcRenderer.invoke(IPC.DECISION_LIST,projectId),add:(projectId,content)=>ipcRenderer.invoke(IPC.DECISION_ADD,projectId,content),remove:id=>ipcRenderer.invoke(IPC.DECISION_REMOVE,id)},
  onAgentEvent(listener){const wrapped=(_e:Electron.IpcRendererEvent,event:AgentEvent)=>listener(event);ipcRenderer.on(IPC.AGENT_EVENT,wrapped);return()=>ipcRenderer.removeListener(IPC.AGENT_EVENT,wrapped)}
}
contextBridge.exposeInMainWorld('crazyParrot',api)

declare global { interface Window { crazyParrot:CrazyParrotApi } }
