export const IPC = {
  APP_VERSION: 'app:version', OPEN_PATH: 'app:open-path', APP_PREFERENCES: 'app:preferences', APP_PREFERENCES_SAVE: 'app:preferences-save', APP_TASK_POLICY: 'app:task-policy', APP_TASK_POLICY_SAVE: 'app:task-policy-save', APP_HISTORY_POLICY: 'app:history-policy', APP_HISTORY_POLICY_SAVE: 'app:history-policy-save', APP_HISTORY_CLEANUP: 'app:history-cleanup', APP_DIAGNOSTICS_EXPORT: 'app:diagnostics-export', APP_UPDATE_CHECK: 'app:update-check', APP_RELEASE_OPEN: 'app:release-open', APPEARANCE_GET: 'appearance:get', APPEARANCE_SAVE: 'appearance:save', APPEARANCE_CHOOSE_BACKGROUND: 'appearance:choose-background',
  PROJECT_LIST: 'project:list', PROJECT_LIST_ARCHIVED: 'project:list-archived', PROJECT_CHOOSE: 'project:choose', PROJECT_ADD: 'project:add', PROJECT_GET: 'project:get', PROJECT_ARCHIVE: 'project:archive', PROJECT_RESTORE: 'project:restore', PROJECT_REMOVE: 'project:remove', PROJECT_FILES: 'project:files', PROJECT_READ_FILE: 'project:read-file',
  PARROT_STATUS: 'parrot:status', PARROT_GENERATE: 'parrot:generate', PARROT_SAVE: 'parrot:save', PARROT_APPROVE: 'parrot:approve', PARROT_VALIDATE: 'parrot:validate', PARROT_AI_OPTIMIZE: 'parrot:ai-optimize', PARROT_AI_OPTIMIZE_EVENT: 'parrot:ai-optimize-event', PARROT_COMPLIANCE: 'parrot:compliance', PARROT_AUDIT: 'parrot:audit',
  PROVIDER_LIST: 'provider:list', PROVIDER_SAVE: 'provider:save', PROVIDER_REMOVE: 'provider:remove', PROVIDER_TEST: 'provider:test', PROVIDER_MODELS: 'provider:models',
  TASK_LIST: 'task:list', TASK_EVENTS: 'task:events', TASK_CREATE: 'task:create', TASK_REORDER: 'task:reorder', TASK_COMPACT: 'task:compact', TASK_APPROVE: 'task:approve', TASK_RESUME: 'task:resume', TASK_CANCEL: 'task:cancel', TASK_REVERT: 'task:revert',
  RECEIPT_LIST: 'receipt:list', RECEIPT_GET: 'receipt:get', RECEIPT_DRIFT: 'receipt:drift', RECEIPT_EXPORT: 'receipt:export',
  SNAPSHOT_LIST: 'snapshot:list', SNAPSHOT_REMOVE: 'snapshot:remove', SNAPSHOT_POLICY: 'snapshot:policy', SNAPSHOT_POLICY_SAVE: 'snapshot:policy-save', SNAPSHOT_STORAGE: 'snapshot:storage', SNAPSHOT_DIFF_CONTENT: 'snapshot:diff-content',
  DECISION_LIST: 'decision:list', DECISION_ADD: 'decision:add', DECISION_REMOVE: 'decision:remove', AGENT_EVENT: 'agent:event'
} as const
